/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crabfood;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class CrustyCrab extends javax.swing.JFrame {
    double totalprice = 0;
    int cookingtime;
    int count = 0;
    Date d = new Date();
    SimpleDateFormat m = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");

    /**
     * Creates new form CrustyCrab
     */
    public CrustyCrab() {
        showDate();
        showTime();
        initComponents();
    }

    void showDate() {
        // Date d = new Date();
        // SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        //  dateLab.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                //  timeLab.setText(s.format(d));
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l33 = new javax.swing.JCheckBox();
        l20 = new javax.swing.JCheckBox();
        l44 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        CrabbyPatty = new javax.swing.JCheckBox();
        CrabbyMeal = new javax.swing.JCheckBox();
        SailorsSurprise = new javax.swing.JCheckBox();
        PlaceOrder = new javax.swing.JButton();
        PlaceOrderMsg = new javax.swing.JLabel();
        PlaceOrderMsg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Select which branch you would like to order from :");

        l33.setText("3 3");
        l33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l33ActionPerformed(evt);
            }
        });

        l20.setText("2 0");

        l44.setText("4 4");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("What dish would you like to order?");

        CrabbyPatty.setText("Crabby Patty $5.00");
        CrabbyPatty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrabbyPattyActionPerformed(evt);
            }
        });

        CrabbyMeal.setText("Crabby Meal  $7.50");
        CrabbyMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrabbyMealActionPerformed(evt);
            }
        });

        SailorsSurprise.setText("Sailors Surprise $6.50");
        SailorsSurprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SailorsSurpriseActionPerformed(evt);
            }
        });

        PlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PlaceOrder.setText("Place Order");
        PlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrabbyMeal)
                    .addComponent(CrabbyPatty)
                    .addComponent(l20)
                    .addComponent(l44)
                    .addComponent(l33)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SailorsSurprise)
                        .addGap(211, 211, 211)
                        .addComponent(PlaceOrder))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlaceOrderMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlaceOrderMsg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l44)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrabbyPatty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrabbyMeal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SailorsSurprise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(PlaceOrder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlaceOrderMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlaceOrderMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l33ActionPerformed
        l33.isSelected();
        //  PlaceOrderMsg.setText(m.format(d)+s.format(d)+": Branch of Crusty Crab at (3,3) takes order.\n");

    }//GEN-LAST:event_l33ActionPerformed

    private void PlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderActionPerformed
        count++;
        if (CrabbyMeal.isSelected() && SailorsSurprise.isSelected() && CrabbyPatty.isSelected()) {
            PlaceOrderMsg.setText("<html>"+m.format(d) + s.format(d) + ": Customer " + count + " wants to order Crabby Patty,<br>Crabby Meal and Sailors Surprise.</html>");
        } else if (CrabbyMeal.isSelected() && SailorsSurprise.isSelected()) {
            PlaceOrderMsg.setText(m.format(d) + s.format(d) + ": Customer " + count + " wants to order Crabby Meal and Sailors Surprise.");
        } else if (CrabbyPatty.isSelected() && SailorsSurprise.isSelected()) {
            PlaceOrderMsg.setText(m.format(d) + s.format(d) + ": Customer " + count + " wants to order Crabby Patty and Sailors Surprise.");
        } else if (CrabbyPatty.isSelected() && CrabbyMeal.isSelected()) {
            PlaceOrderMsg.setText(m.format(d) + s.format(d) + ": Customer " + count + " wants to order Crabby Patty and Crabby Meal.");
        } else if (SailorsSurprise.isSelected()) {
            PlaceOrderMsg.setText(m.format(d) + s.format(d) + ": Customer " + count + " wants to order Sailors Surprise.");
        } else if (CrabbyMeal.isSelected()) {
            PlaceOrderMsg.setText(m.format(d) + s.format(d) + ": Customer " + count + " wants to order Crabby Meal.");
        } else if (CrabbyPatty.isSelected()) {
            PlaceOrderMsg.setText(m.format(d) + s.format(d) + ": Customer " + count + " wants to order Crabby Patty.");
        }

        if (l33.isSelected()) {
            PlaceOrderMsg2.setText(m.format(d) + s.format(d) + ": Branch of Crusty Crab at (3,3) takes order.");
        }
        if (l20.isSelected()) {
            PlaceOrderMsg2.setText(m.format(d) + s.format(d) + ": Branch of Crusty Crab at (2,0) takes order.");
        }
        if (l44.isSelected()) {
            PlaceOrderMsg2.setText(m.format(d) + s.format(d) + ": Branch of Crusty Crab at (4,4) takes order.");
        }
    }//GEN-LAST:event_PlaceOrderActionPerformed

    private void CrabbyPattyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrabbyPattyActionPerformed
        CrabbyPatty.isSelected();
        cookingtime+=20;
        totalprice += 5.00;
        //PlaceOrderMsg.setText(m.format(d)+s.format(d)+": Customer "+count+": wants to order Crabby Patty\n");           

    }//GEN-LAST:event_CrabbyPattyActionPerformed

    private void CrabbyMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrabbyMealActionPerformed
        // TODO add your handling code here:
        cookingtime+=20;
        totalprice += 7.50;
    }//GEN-LAST:event_CrabbyMealActionPerformed

    private void SailorsSurpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SailorsSurpriseActionPerformed
        // TODO add your handling code here:
        cookingtime+=20;
        totalprice += 6.50;
    }//GEN-LAST:event_SailorsSurpriseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrustyCrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrustyCrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrustyCrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrustyCrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrustyCrab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CrabbyMeal;
    private javax.swing.JCheckBox CrabbyPatty;
    private javax.swing.JButton PlaceOrder;
    private javax.swing.JLabel PlaceOrderMsg;
    private javax.swing.JLabel PlaceOrderMsg2;
    private javax.swing.JCheckBox SailorsSurprise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox l20;
    private javax.swing.JCheckBox l33;
    private javax.swing.JCheckBox l44;
    // End of variables declaration//GEN-END:variables
}
